services:
  - name: nestjs-app
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    buildCommandPreRun: 
      - command: npx prisma migrate dev
        dir: /app